name: Lint

on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            # ESLint and Prettier must be in `package.json`
            - name: Install Node.js dependencies
              run: yarn

            - name: Run linters
              uses: wearerequired/lint-action@v1
              with:
                  eslint: true
                  eslint_extensions: ts,tsx
                  prettier: true
                  prettier_extensions: js,ts,tsx
                  prettier_dir: src/

            - name: Run tests
              uses: mattallty/jest-github-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  test-command: 'yarn test'
                  coverage-comment: false
